baseURL = '/'
languageCode = 'en-us'
title = 'Donald Jenkins is a writer and photographer'
description = "Donald Jenkins writes, takes photographs and dabbles in web design. He’s also a co-founder of the political social network start-up Policymakr."
summary = "Donald read Philosophy, Politics and Economics at Magdalen College, Oxford, and government at École nationale d’administration. He has worked in merchant banking, the media, public administration and contemporary art. His main subjects of interest and concern are the environment, animal rights, politics and technology. He rides a bicycle and is a vegan."

# Sets homepage meta description (for SEO)

rssTitle = "Donald Jenkins"
# Sets RSS feed title (for RSS readers)

seoTitle = "Donald Jenkins is a writer and photographer"
# Sets homepage <title> (for SEO)

# disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = 'true'
# relativeURLs = 'true'
contentDir = 'content'
enableInlineShortcodes = true
enableGitInfo = true
enableRobotsTXT = true

[permalinks] 
articles = "/:slug"

[params]
    stylesheets = ["main.css"]
    cloudflare_images = "https://www.silverejarrosson.com/cdn-cgi/imagedelivery/L0HrrfgxmX01pIlKW6n82w/"
    
[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5
    
[build]
    writeStats = true

[[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-pro/scss"
  target = "assets/scss/fontawesome"
  
  color = "#9c9a75"
  # Sets theme colour& Safari mask icon colour
  
  [markup.goldmark.renderer]
      unsafe = true # Allow HTML in md files
