baseURL = 'https://www.donaldjenkins.com/'
languageCode = 'en-gb'
timeZone = 'America/New_York'
title = 'Donald Jenkins writes about politics'
rssTitle = "Donald Jenkins"
# Sets RSS feed title (for RSS readers)

seoTitle = "Donald Jenkins writes about politics"
# Sets homepage <title> (for SEO)

# disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = 'true'
# relativeURLs = 'true'
contentDir = 'content'
enableInlineShortcodes = true
enableGitInfo = true
enableRobotsTXT = true

# Source: https://mertbakir.gitlab.io/hugo/last-modified-date-in-hugo/
[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

[params]
  stylesheets = ["styles.css"]
  taxonomiesExcludedFromSitemap = ["tags", "categories"]
  color = "#9c9a75"
  # Sets theme colour& Safari mask icon colour
  cloudflare_images = "https://www.donaldjenkins.com/cdn-cgi/imagedelivery/L0HrrfgxmX01pIlKW6n82w/"
  assets_url = "https://assets.donaldjenkins.com/"
  video_url = "https://customer-j00pa75eocpcmpyc.cloudflarestream.com/"
  video_suffix = "/manifest/video.m3u8"
  thumbnail_suffix = "/thumbnails/thumbnail.jpg?time="
  assets_thumbnails = "https://assets.donaldjenkins.com/images/thumbnails/"
  flickr_images = "https://flickr.com/photos/astorg/"
  flickr_suffix = "/in/dateposted-public/"
  description = "Donald Jenkins [writes](/articles/), inter alia, about [politics](/politics/). He co-founded [Policymakr](https://policymakr.com/), an online think-tank.  He takes [photographs](/photos/) and tweets as [@donaldjenkins](https://www.twitter.com/donaldjenkins)."
  seo_description = "Donald Jenkins writes, among other matters, about politics. He co-founded Policymakr, an online think-tank. He lives in New York."
  about = "I read Philosophy, Politics and Economics at [Magdalen College, Oxford](https://www.magd.ox.ac.uk/), and government at [École nationale d’administration](https://en.wikipedia.org/wiki/%C3%89cole_nationale_d%27administration). I have worked in [merchant banking](https://en.wikipedia.org/wiki/Merchant_bank), the [media](https://www.rfi.fr/), [public administration](https://www.culture.gouv.fr/) and [contemporary art](https://www.centrepompidou.fr/en). My main subjects of interest and concern are the [environment](https://nymag.com/intelligencer/2018/10/un-says-climate-genocide-coming-but-its-worse-than-that.html), [animal rights](/non-human-animal-rights-the-categorical-imperative-of-our-time/), [politics](/category/politics/) and [technology](/category/tech/). I ride a bicycle and am a [vegan.](/non-human-animal-rights-the-categorical-imperative-of-our-time/)"

[module]
[[module.mounts]]
  source = "static"
  target = "static"
[[module.mounts]]
  source = "node_modules/vidstack"
  target = "static/vidstack"

[taxonomies]  
  category = "categories"
  tag = "tags"

[permalinks] 
articles = "/:slug"
categories= "/:slug/"
    
[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5
    
[build]
  writeStats = true
  
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
