baseURL = 'https://www.donaldjenkins.com/'
languageCode = 'en-gb'
timeZone = 'America/New_York'
title = 'Donald Jenkins writes about politics'

[params]
  stylesheets = ["styles.css"]
  taxonomiesExcludedFromSitemap = ["tags", "categories"]
  color = "#9c9a75"
  # Sets theme colour& Safari mask icon colour
  cloudflare_images = "https://www.donaldjenkins.com/cdn-cgi/imagedelivery/L0HrrfgxmX01pIlKW6n82w/"
  assets_url = "https://assets.donaldjenkins.com/"
  video_url = "https://customer-j00pa75eocpcmpyc.cloudflarestream.com/"
  video_suffix = "/manifest/video.m3u8"
  thumbnail_suffix = "/thumbnails/thumbnail.jpg?time="
  assets_thumbnails = "https://assets.donaldjenkins.com/images/thumbnails/"
  flickr_images = "https://flickr.com/photos/astorg/"
  flickr_suffix = "/in/dateposted-public/"
  description = "Donald Jenkins [writes](/articles/), among other matters, about [politics](/politics/). He co-founded [Policymakr](https://policymakr.com/), an online think-tank.  He lives in New York and also takes [photographs](/photos/)."
  seo_description = "Donald Jenkins writes, among other matters, about politics. He co-founded Policymakr, an online think-tank. He lives in New York."
  about = "I read Philosophy, Politics and Economics at [Magdalen College, Oxford](https://www.magd.ox.ac.uk/), and government at [École nationale d’administration](https://en.wikipedia.org/wiki/%C3%89cole_nationale_d%27administration). I have worked in [merchant banking](https://en.wikipedia.org/wiki/Merchant_bank), the [media](https://www.rfi.fr/), [public administration](https://www.culture.gouv.fr/) and [contemporary art](https://www.centrepompidou.fr/en). My main subjects of interest and concern are the [environment](https://nymag.com/intelligencer/2018/10/un-says-climate-genocide-coming-but-its-worse-than-that.html), [animal rights](/non-human-animal-rights-the-categorical-imperative-of-our-time/), [politics](/category/politics/) and [technology](/category/tech/). I ride a bicycle and am a [vegan.](/non-human-animal-rights-the-categorical-imperative-of-our-time/)"
  summary = "As evidenced by the selection of articles and by the tag list above, I write about a wide range of interests. In recent years these have mainly focused on British and French politics, and on my [geeky path](https://github.com/donaldjenkins) as a code writer."
  [categories]
    personal = "This includes a wide range of miscellaneous topics—inevitably inducing an impression of boundless eclecticism."
    culture = "My interests span contemporary art, which has surrounded me ever since my infancy,[heraldry]({{% assets documents %}}jenkins-arms-large.jpg), music, especially from Mozart up to the mid-Romantic period, as well as well-sung English choral music from the sixteenth, seventeenth and nineteenth centuries. I have worked in the field of culture and media in various capacities."
    politics = "Politics are hardly a side interest, as can be seen from the articles collected here. I first indulged my taste for [politics](/politics/) **and current affairs at Oxford at the** [Oxford Union Society](http://www.oxford-union.org/), and then as a student in Paris, where I was President of [Conférence Olivaint](http://en.wikipedia.org/wiki/Conférence_Olivaint)."
    tech = "Subjects I’m passionate about include [code](https://stackoverflow.com/users/265324/donald-jenkins)**, good** [web design](https://dribbble.com/donaldjenkins), Net neutrality, and avoiding government interference in the Internet. I write a lot about  Apple-related stuff, blogging techniques and trends in social networks."
    literature = "My favourite authors are those who wrote after the turn of the nineteenth century, but before the death of Camus, which still leaves quite a wide range. This happens to coincide with the so-called période grammaticale, a period during which form was deemed to matter more than substance, not because substance did not matter, but because form was the surest way of gauging the true value of the substance behind it—a view with which I heartily agree."
    religion = "Like the first Queen Elizabeth, I firmly believe in not putting windows into men’s souls (oral tradition, the words very possibly originating in a letter drafted by Bacon; in J. B. Black _Reign of Elizabeth 1558–1603_ [1936]). Yet like the second Queen of the same name, I take my religion (relatively) seriously and have occasionally shared thoughts about the subject here."
    sundry = "These articles don’t fit neatly into this site’s topics. Their presence here probably bears witness the incorrigible eclecticity of my range of interests."

rssTitle = "Donald Jenkins"
# Sets RSS feed title (for RSS readers)

seoTitle = "Donald Jenkins writes about politics"
# Sets homepage <title> (for SEO)

# disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = 'true'
# relativeURLs = 'true'
contentDir = 'content'
enableInlineShortcodes = true
enableGitInfo = true
enableRobotsTXT = true

[module]
[[module.mounts]]
  source = "static"
  target = "static"
[[module.mounts]]
  source = "node_modules/vidstack"
  target = "static/vidstack"

[taxonomies]  
  category = "categories"
  tag = "tags"

[permalinks] 
articles = "/:slug"
categories= "/:slug/"
    
[sitemap]
  changefreq = 'always'
  filename = 'sitemap.xml'
  priority = 0.5
    
[build]
  writeStats = true
  
[markup.goldmark.renderer]
  unsafe = true # Allow HTML in md files
