baseURL = 'https://donaldjenkins.pages.dev/'
languageCode = 'en-us'
timeZone = 'America/New_York'
title = 'Donald Jenkins writes about politics'

[params]
  stylesheets = ["styles.css"]
  cloudflare_images = "https://www.silverejarrosson.com/cdn-cgi/imagedelivery/L0HrrfgxmX01pIlKW6n82w/"
  description = "Donald Jenkins [writes](https://www.donaldjenkins.com/articles/), among other matters, about [politics](/category/politics), and co-founded [Policymakr](http://policymakr.com/), an online think-tank.  He lives in New York and also takes [photographs](https://www.donaldjenkins.com/photos/)."
  summary = "Donald read Philosophy, Politics and Economics at [Magdalen College, Oxford](http://www.magd.ox.ac.uk/), and government at [École nationale d’administration](https://www.ena.fr/). He has worked in [merchant banking](https://en.wikipedia.org/wiki/Merchant_bank), the [media](http://www.rfi.fr/), [public administration](http://www.culture.gouv.fr/) and [contemporary art](https://www.centrepompidou.fr/en). His main subjects of interest and concern are the [environment](http://nymag.com/intelligencer/2018/10/un-says-climate-genocide-coming-but-its-worse-than-that.html), [animal rights](https://www.donaldjenkins.com/non-human-animal-rights-the-categorical-imperative-of-our-time/), [politics](https://www.donaldjenkins.com/category/politics/) and [technology](https://www.donaldjenkins.com/category/tech/). He rides a bicycle and is a [vegan.](https://www.donaldjenkins.com/non-human-animal-rights-the-categorical-imperative-of-our-time/)"

# Sets homepage meta description (for SEO)

rssTitle = "Donald Jenkins"
# Sets RSS feed title (for RSS readers)

seoTitle = "Donald Jenkins is a writer and photographer"
# Sets homepage <title> (for SEO)

# disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = 'true'
# relativeURLs = 'true'
contentDir = 'content'
enableInlineShortcodes = true
enableGitInfo = true
enableRobotsTXT = true

[permalinks] 
articles = "/:slug"
    
[sitemap]
    changefreq = 'monthly'
    filename = 'sitemap.xml'
    priority = 0.5
    
[build]
    writeStats = true

[[module.mounts]]
  source = "node_modules/@fortawesome/fontawesome-pro/scss"
  target = "assets/scss/fontawesome"
  
color = "#9c9a75"
  # Sets theme colour& Safari mask icon colour
  
[markup.goldmark.renderer]
      unsafe = true # Allow HTML in md files
